---
- hosts: localhost
  gather_facts: no
  connection: local

  # 変数設定
  vars_files:
    - vars/main.yml

  # インストール
  roles:
    - homebrew
    - pip
    - ohmyzsh
    - powerline-fonts
    - dotfiles
#    - ssh-keygen
#    - atom-packages
#    - gem
    - npm
    - gcloud
#    - code
