---
- hosts: localhost
  user: hishikiy
  gather_facts: no
  connection: local

  # 変数設定
  vars_files:
    - vars/main.yml

  # 事前セットアップ
  tasks:
    - include: tasks/ansible-setup.yml

  # インストール
  roles:
    - homebrew
    - pip
#    - dotfiles
#    - atom-packages
    - gem
    - npm
    - gcloud
    - code
