---
# tasks file for npm

- name: Ensure configured node.js packages are installed.
#  gem: "name={{ item }} executable=/usr/local/bin state=latest"
  npm: "name={{ item }} state=latest global=yes"
  sudo: yes
  with_items: '{{ npm_installed_packages }}'
