---
- name: Copy dotfiles.
  copy:
    src: "{{ lookup('env', 'PWD') }}/{{ dotfiles_origin }}/{{ item }}"
    dest: "{{ lookup('env', 'HOME') }}/{{ item }}"
    owner: "{{ lookup('env', 'USER') }}"
    group: staff
    mode: 0644
  with_items:
    - "{{ dotfiles_files }}"
