---
# pip.
- name: Ensure configured python packages are installed.
  pip: "name={{ item.name }}  state=present"
  with_items: '{{ pip_installed_packages }}'

#- name: Upgrade all python packages (if configured).
#  pip: update_pip=yes upgrade_all=yes
#  when: '{{ pip_upgrade_all_packages }}'
