---
# Tap.
- name: Ensure configured taps are tapped.
  homebrew_tap: "tap={{ item }} state=present"
  with_items: "{{ homebrew_taps }}"

# Brew.
- name: Ensure configured homebrew packages are installed.
  homebrew:
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
  with_items: "{{ homebrew_installed_packages }}"

- name: Upgrade all homebrew packages (if configured).
  homebrew: update_homebrew=yes upgrade_all=yes
  when: "homebrew_upgrade_all_packages"

# Cask.
- name: Get list of apps installed with cask.
  command: bash -l -c '{{ homebrew_brew_bin_path }}/brew list --cask'
  register: homebrew_cask_list

# Use command module instead of homebrew_cask so appdir can be used.
- name: Install configured cask applications.
  community.general.homebrew_cask:
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
    install_options: 'appdir=/Applications'
  with_items: "{{ homebrew_cask_apps }}"
  when: "item.name not in homebrew_cask_list.stdout"
