---
# tasks file for gem

- name: Ensure configured ruby packages are installed.
#  gem: "name={{ item }} executable=/usr/local/bin state=latest"
  gem: "name={{ item }} state=latest"
  become: yes
  with_items: '{{ gem_installed_packages }}'
